export const qgisServerConfig = {
  baseUrl: "http://localhost:8080/ows/",
  projectPath: "/io/workspace/CLEAN GIS/CLEAN GIS.qgz",
};

export const qgisWmsLayers = {
  scotlandHexGrid: "dashboard_hex_master_complete",
  companyConcentration: "Company concentration",
  totalDependency: "Average dependency",
  totalPressure: "Average pressure",
  depAirFiltration: "Air filtration",
  depBiologicalControl: "Biological control",
  depBiomassProvisioning: "Biomass provisioning",
  depEducationScientificResearchServices: "Education scientific and research services",
  depFloodControl: "Flood control",
  depGeneticMaterial: "Genetic material",
  depGlobalClimateRegulation: "Global climate regulation",
  depLocalClimateRegulation: "Local climate regulation",
  depNoiseAttenuation: "Noise attenuation",
  depNurseryHabitatMaintenance: "Nursery population and habitat maintenance",
  depAnimalBasedEnergy: "Animal-based energy",
  depDilutionAtmosphereEcosystems: "Dilution by atmosphere and ecosystems",
  depMediationSensoryImpacts: "Mediation of sensory impacts",
  depPollination: "Pollination",
  depRainfallPatternRegulation: "Rainfall pattern regulation",
  depRecreationRelatedServices: "Recreation-related services",
  depSoilSedimentRetention: "Soil and sediment retention",
  depSoilQualityRegulation: "Soil quality regulation",
  depSolidWasteRemediation: "Solid-waste remediation",
  depSpiritualArtisticSymbolicServices: "Spiritual artistic and symbolic services",
  depStormMitigation: "Storm mitigation",
  depVisualAmenityServices: "Visual amenity services",
  depWaterFlowRegulation: "Water-flow regulation",
  depWaterPurification: "Water purification",
  depWaterSupply: "Water supply",
  pressFreshwaterAreaUse: "Freshwater area use",
  pressLandUse: "Land use",
  pressSeabedUse: "Seabed use",
  pressWaterUse: "Water use",
  pressBioticResourceExtraction: "Biotic resource extraction",
  pressAbioticResourceExtraction: "Abiotic resource extraction",
  pressGreenhouseGasEmissions: "Greenhouse-gas emissions",
  pressNonGhgAirPollutants: "Non-GHG air pollutants",
  pressNutrientSoilWaterPollutants: "Nutrient soil and water pollutants",
  pressToxicSoilWaterPollutants: "Toxic soil and water pollutants",
  pressSolidWasteGeneration: "Solid-waste generation",
  pressIntroductionOfInvasiveSpecies: "Introduction of invasive species",
  pressDisturbanceNoiseLight: "Disturbance: noise and light",
  nationalNatureReserves: "National Nature Reserves",
  sssi: "Sites of Special Scientific Interest (SSSI)",
  lochLomondAndTrossachsNationalPark: "Loch Lomond & Trossachs National Park",
  cairngormsNationalPark: "Cairngorms National Park",
  wildLandAreas: "Wild Land Areas",
  worldHeritageSites: "World Heritage Sites",
  scotlandBoundary: "Scotland Boundary",
};
